spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver

  jooq:
    sql-dialect: org.hibernate.dialect.H2Dialect

  jpa:
    hibernate:
      ddl-auto: create

rtt:
  trigger:
    chunk-size: 2