spring:
  profiles:
    active: local-development

rtt:
  trigger:
    chunk-size: 10

scheduler-routes:
  collector:
    id: CollectorSchedulerRoute
    cron-expression: 0/20 * * ? * * *
    thread-pool: 10

  trigger:
    id: TriggerSchedulerRoute
    cron-expression: 0/10 * * ? * * *
    thread-pool: 10

  bothub-trigger:
    thread-pool: 10

  bothub-collector:
    thread-pool: 10
